# Inherit from Hound default configuration so we can perform the same
# checks locally.
inherit_from: ./.rubocop_hound.yml

AllCops:
  TargetRubyVersion: 2.1

# Use double quotes only for interpolation.
Style/StringLiterals:
  EnforcedStyle: single_quotes

# Place dots at the beginning of multiline method calls.
Style/DotPosition:
  EnforcedStyle: leading

# The default of 80 characters is a little to narrow.
Metrics/LineLength:
  Max: 100

# Only place spaces inside blocks written with braces.
Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
